-- MySQL Script generated by MySQL Workbench
-- Thu Aug 31 12:06:45 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proxiBdD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proxiBdD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proxiBdD` DEFAULT CHARACTER SET utf8 ;
USE `proxiBdD` ;

-- -----------------------------------------------------
-- Table `proxiBdD`.`conseilleClient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proxiBdD`.`conseilleClient` (
  `id_cons` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `no_agence` INT NULL,
  PRIMARY KEY (`id_cons`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proxiBdD`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proxiBdD`.`client` (
  `id_client` INT NOT NULL,
  `id_cons` INT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `code_postal` INT NULL,
  `ville` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  INDEX `id_cons_idx` (`id_cons` ASC),
  PRIMARY KEY (`id_client`),
  CONSTRAINT `id_cons`
    FOREIGN KEY (`id_cons`)
    REFERENCES `proxiBdD`.`conseilleClient` (`id_cons`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proxiBdD`.`comptes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proxiBdD`.`comptes` (
  `n_cpte` INT NOT NULL,
  `solde` DOUBLE NULL,
  `type` INT NULL,
  `ouverture` DATE NULL,
  PRIMARY KEY (`n_cpte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proxiBdD`.`portefeuille`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proxiBdD`.`portefeuille` (
  `id_cpt` INT NOT NULL,
  `id_cl` INT NOT NULL,
  INDEX `id_client_idx` (`id_cl` ASC),
  PRIMARY KEY (`id_cpt`, `id_cl`),
  CONSTRAINT `id_client`
    FOREIGN KEY (`id_cl`)
    REFERENCES `proxiBdD`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `n_cpte`
    FOREIGN KEY (`id_cpt`)
    REFERENCES `proxiBdD`.`comptes` (`n_cpte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `proxiBdD`.`conseilleClient`
-- -----------------------------------------------------
START TRANSACTION;
USE `proxiBdD`;
INSERT INTO `proxiBdD`.`conseilleClient` (`id_cons`, `nom`, `prenom`, `no_agence`) VALUES (1, 'Burel', 'sebastien', 1);
INSERT INTO `proxiBdD`.`conseilleClient` (`id_cons`, `nom`, `prenom`, `no_agence`) VALUES (2, 'Torres', 'ludovic', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `proxiBdD`.`client`
-- -----------------------------------------------------
START TRANSACTION;
USE `proxiBdD`;
INSERT INTO `proxiBdD`.`client` (`id_client`, `id_cons`, `nom`, `prenom`, `adresse`, `code_postal`, `ville`, `telephone`) VALUES (10001, 1, 'Botha', 'bakkies', '1 rue du passage', 83000, 'Toulon', NULL);
INSERT INTO `proxiBdD`.`client` (`id_client`, `id_cons`, `nom`, `prenom`, `adresse`, `code_postal`, `ville`, `telephone`) VALUES (10002, 1, 'Wilkinson', 'johnny', '44 impasse du val', 83200, 'Toulon', NULL);
INSERT INTO `proxiBdD`.`client` (`id_client`, `id_cons`, `nom`, `prenom`, `adresse`, `code_postal`, `ville`, `telephone`) VALUES (10003, 2, 'Smith', 'juan', '7 rue de la', 31000, 'Toulouse', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `proxiBdD`.`comptes`
-- -----------------------------------------------------
START TRANSACTION;
USE `proxiBdD`;
INSERT INTO `proxiBdD`.`comptes` (`n_cpte`, `solde`, `type`, `ouverture`) VALUES (10054890, 1000, 1, '');
INSERT INTO `proxiBdD`.`comptes` (`n_cpte`, `solde`, `type`, `ouverture`) VALUES (10054891, -4200, 2, '');
INSERT INTO `proxiBdD`.`comptes` (`n_cpte`, `solde`, `type`, `ouverture`) VALUES (10054892, 500, 3, NULL);
INSERT INTO `proxiBdD`.`comptes` (`n_cpte`, `solde`, `type`, `ouverture`) VALUES (10054893, 1000, 1, NULL);
INSERT INTO `proxiBdD`.`comptes` (`n_cpte`, `solde`, `type`, `ouverture`) VALUES (10054896, 50, 2, NULL);
INSERT INTO `proxiBdD`.`comptes` (`n_cpte`, `solde`, `type`, `ouverture`) VALUES (10054897, -500, 3, NULL);

COMMIT;

